repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.4.2"
    hooks:
      - id: black
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.12
  - repo: https://github.com/pycqa/flake8
    rev: "7.1.0"
    hooks:
      - id: flake8
        args: ['--max-line-length=88']
        exclude: docs/conf.py

  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
        name: isort (python)
        args: ['--check-only', '--profile=black']
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.3.3"
    hooks:
    -   id: python-safety-dependencies-check
        files: ./pyproject.toml
        args: ['check', '--file=.safety-policy.yml']
